const spade = ["Ace of Spades", "Two of Spades", "Three of Spades", "Four of Spades", "Five of Spades", "Six of Spades", "Seven of Spades", "Eight of Spades", "Nine of Spades", "Ten of Spades", "Jack of Spades", "Queen of Spades", "King of Spades"]
const heart = ["Ace of Hearts", "Two of Hearts", "Three of Hearts", "Four of Hearts", "Five of Hearts", "Six of Hearts", "Seven of Hearts", "Eight of Hearts", "Nine of Hearts", "Ten of Hearts", "Jack of Hearts", "Queen of Hearts", "King of Hearts"]
const club =["Ace of Clubs", "Two of Clubs", "Three of Clubs", "Four of Clubs", "Five of Clubs", "Six of Clubs"," Seven of Clubs", "Eight of Clubs", "Nine of Clubs", "Ten of Clubs", "Jack of Clubs",  "Queen of Clubs", "King of Clubs"]
const diamond = ["Ace of Diamonds", "Two of Diamonds", "Three of Diamonds", "Four of Diamonds", "Five of Diamonds", "Six of Diamonds", "Seven of Diamonds", "Eight of Diamonds", "Nine of Diamonds", "Ten of Diamonds", "Jack of Diamonds", "Queen of Diamonds", "King of Diamonds"];
document.getElementById("cardpick").onclick = function() {
  var rand1 = Math.floor(Math.random() * 13);
  var rand2 = Math.floor(Math.random() * 13);
  var rand3 = Math.floor(Math.random() * 13);
  var rand4 = Math.floor(Math.random() * 13);
  var card1 = spade[rand1];
  var card2 = heart[rand2];
  var card3 = club[rand3];
  var card4 = diamond[rand4];
  document.getElementById('secret0').innerHTML = 'Here are your four cards:';
  document.getElementById('secret1').innerHTML = card1;
  document.getElementById('secret2').innerHTML = card2;
  document.getElementById('secret3').innerHTML = card3;
  document.getElementById('secret4').innerHTML = card4;
}
